name: PPUU
channels:
  - pytorch
  - defaults
dependencies:
  - imageio
  - pandas
  - python=3.7
  - pytorch=1.0.1
  - scipy=1.2.0
  - scikit-learn
  - matplotlib
  - pip
  - jupyter
  - pip:
    - gym
    - pygame
    - jupytext
    - ipdb
